
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Artist.ts'
export type * from './models/Instrument.ts'
export type * from './models/Style.ts'
export type * from './commonInputTypes.ts'