
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Style` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Style
 * 
 */
export type StyleModel = runtime.Types.Result.DefaultSelection<Prisma.$StylePayload>

export type AggregateStyle = {
  _count: StyleCountAggregateOutputType | null
  _avg: StyleAvgAggregateOutputType | null
  _sum: StyleSumAggregateOutputType | null
  _min: StyleMinAggregateOutputType | null
  _max: StyleMaxAggregateOutputType | null
}

export type StyleAvgAggregateOutputType = {
  id: number | null
}

export type StyleSumAggregateOutputType = {
  id: number | null
}

export type StyleMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type StyleMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type StyleCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type StyleAvgAggregateInputType = {
  id?: true
}

export type StyleSumAggregateInputType = {
  id?: true
}

export type StyleMinAggregateInputType = {
  id?: true
  name?: true
}

export type StyleMaxAggregateInputType = {
  id?: true
  name?: true
}

export type StyleCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type StyleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Style to aggregate.
   */
  where?: Prisma.StyleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Styles to fetch.
   */
  orderBy?: Prisma.StyleOrderByWithRelationInput | Prisma.StyleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StyleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Styles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Styles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Styles
  **/
  _count?: true | StyleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StyleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StyleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StyleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StyleMaxAggregateInputType
}

export type GetStyleAggregateType<T extends StyleAggregateArgs> = {
      [P in keyof T & keyof AggregateStyle]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStyle[P]>
    : Prisma.GetScalarType<T[P], AggregateStyle[P]>
}




export type StyleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StyleWhereInput
  orderBy?: Prisma.StyleOrderByWithAggregationInput | Prisma.StyleOrderByWithAggregationInput[]
  by: Prisma.StyleScalarFieldEnum[] | Prisma.StyleScalarFieldEnum
  having?: Prisma.StyleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StyleCountAggregateInputType | true
  _avg?: StyleAvgAggregateInputType
  _sum?: StyleSumAggregateInputType
  _min?: StyleMinAggregateInputType
  _max?: StyleMaxAggregateInputType
}

export type StyleGroupByOutputType = {
  id: number
  name: string
  _count: StyleCountAggregateOutputType | null
  _avg: StyleAvgAggregateOutputType | null
  _sum: StyleSumAggregateOutputType | null
  _min: StyleMinAggregateOutputType | null
  _max: StyleMaxAggregateOutputType | null
}

type GetStyleGroupByPayload<T extends StyleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StyleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StyleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StyleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StyleGroupByOutputType[P]>
      }
    >
  >



export type StyleWhereInput = {
  AND?: Prisma.StyleWhereInput | Prisma.StyleWhereInput[]
  OR?: Prisma.StyleWhereInput[]
  NOT?: Prisma.StyleWhereInput | Prisma.StyleWhereInput[]
  id?: Prisma.IntFilter<"Style"> | number
  name?: Prisma.StringFilter<"Style"> | string
  artists?: Prisma.ArtistListRelationFilter
}

export type StyleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  artists?: Prisma.ArtistOrderByRelationAggregateInput
}

export type StyleWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.StyleWhereInput | Prisma.StyleWhereInput[]
  OR?: Prisma.StyleWhereInput[]
  NOT?: Prisma.StyleWhereInput | Prisma.StyleWhereInput[]
  name?: Prisma.StringFilter<"Style"> | string
  artists?: Prisma.ArtistListRelationFilter
}, "id">

export type StyleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.StyleCountOrderByAggregateInput
  _avg?: Prisma.StyleAvgOrderByAggregateInput
  _max?: Prisma.StyleMaxOrderByAggregateInput
  _min?: Prisma.StyleMinOrderByAggregateInput
  _sum?: Prisma.StyleSumOrderByAggregateInput
}

export type StyleScalarWhereWithAggregatesInput = {
  AND?: Prisma.StyleScalarWhereWithAggregatesInput | Prisma.StyleScalarWhereWithAggregatesInput[]
  OR?: Prisma.StyleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StyleScalarWhereWithAggregatesInput | Prisma.StyleScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Style"> | number
  name?: Prisma.StringWithAggregatesFilter<"Style"> | string
}

export type StyleCreateInput = {
  name: string
  artists?: Prisma.ArtistCreateNestedManyWithoutStylesInput
}

export type StyleUncheckedCreateInput = {
  id?: number
  name: string
  artists?: Prisma.ArtistUncheckedCreateNestedManyWithoutStylesInput
}

export type StyleUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.ArtistUpdateManyWithoutStylesNestedInput
}

export type StyleUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.ArtistUncheckedUpdateManyWithoutStylesNestedInput
}

export type StyleCreateManyInput = {
  id?: number
  name: string
}

export type StyleUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StyleUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StyleListRelationFilter = {
  every?: Prisma.StyleWhereInput
  some?: Prisma.StyleWhereInput
  none?: Prisma.StyleWhereInput
}

export type StyleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StyleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type StyleAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StyleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type StyleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type StyleSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StyleCreateNestedManyWithoutArtistsInput = {
  create?: Prisma.XOR<Prisma.StyleCreateWithoutArtistsInput, Prisma.StyleUncheckedCreateWithoutArtistsInput> | Prisma.StyleCreateWithoutArtistsInput[] | Prisma.StyleUncheckedCreateWithoutArtistsInput[]
  connectOrCreate?: Prisma.StyleCreateOrConnectWithoutArtistsInput | Prisma.StyleCreateOrConnectWithoutArtistsInput[]
  connect?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
}

export type StyleUncheckedCreateNestedManyWithoutArtistsInput = {
  create?: Prisma.XOR<Prisma.StyleCreateWithoutArtistsInput, Prisma.StyleUncheckedCreateWithoutArtistsInput> | Prisma.StyleCreateWithoutArtistsInput[] | Prisma.StyleUncheckedCreateWithoutArtistsInput[]
  connectOrCreate?: Prisma.StyleCreateOrConnectWithoutArtistsInput | Prisma.StyleCreateOrConnectWithoutArtistsInput[]
  connect?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
}

export type StyleUpdateManyWithoutArtistsNestedInput = {
  create?: Prisma.XOR<Prisma.StyleCreateWithoutArtistsInput, Prisma.StyleUncheckedCreateWithoutArtistsInput> | Prisma.StyleCreateWithoutArtistsInput[] | Prisma.StyleUncheckedCreateWithoutArtistsInput[]
  connectOrCreate?: Prisma.StyleCreateOrConnectWithoutArtistsInput | Prisma.StyleCreateOrConnectWithoutArtistsInput[]
  upsert?: Prisma.StyleUpsertWithWhereUniqueWithoutArtistsInput | Prisma.StyleUpsertWithWhereUniqueWithoutArtistsInput[]
  set?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
  disconnect?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
  delete?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
  connect?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
  update?: Prisma.StyleUpdateWithWhereUniqueWithoutArtistsInput | Prisma.StyleUpdateWithWhereUniqueWithoutArtistsInput[]
  updateMany?: Prisma.StyleUpdateManyWithWhereWithoutArtistsInput | Prisma.StyleUpdateManyWithWhereWithoutArtistsInput[]
  deleteMany?: Prisma.StyleScalarWhereInput | Prisma.StyleScalarWhereInput[]
}

export type StyleUncheckedUpdateManyWithoutArtistsNestedInput = {
  create?: Prisma.XOR<Prisma.StyleCreateWithoutArtistsInput, Prisma.StyleUncheckedCreateWithoutArtistsInput> | Prisma.StyleCreateWithoutArtistsInput[] | Prisma.StyleUncheckedCreateWithoutArtistsInput[]
  connectOrCreate?: Prisma.StyleCreateOrConnectWithoutArtistsInput | Prisma.StyleCreateOrConnectWithoutArtistsInput[]
  upsert?: Prisma.StyleUpsertWithWhereUniqueWithoutArtistsInput | Prisma.StyleUpsertWithWhereUniqueWithoutArtistsInput[]
  set?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
  disconnect?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
  delete?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
  connect?: Prisma.StyleWhereUniqueInput | Prisma.StyleWhereUniqueInput[]
  update?: Prisma.StyleUpdateWithWhereUniqueWithoutArtistsInput | Prisma.StyleUpdateWithWhereUniqueWithoutArtistsInput[]
  updateMany?: Prisma.StyleUpdateManyWithWhereWithoutArtistsInput | Prisma.StyleUpdateManyWithWhereWithoutArtistsInput[]
  deleteMany?: Prisma.StyleScalarWhereInput | Prisma.StyleScalarWhereInput[]
}

export type StyleCreateWithoutArtistsInput = {
  name: string
}

export type StyleUncheckedCreateWithoutArtistsInput = {
  id?: number
  name: string
}

export type StyleCreateOrConnectWithoutArtistsInput = {
  where: Prisma.StyleWhereUniqueInput
  create: Prisma.XOR<Prisma.StyleCreateWithoutArtistsInput, Prisma.StyleUncheckedCreateWithoutArtistsInput>
}

export type StyleUpsertWithWhereUniqueWithoutArtistsInput = {
  where: Prisma.StyleWhereUniqueInput
  update: Prisma.XOR<Prisma.StyleUpdateWithoutArtistsInput, Prisma.StyleUncheckedUpdateWithoutArtistsInput>
  create: Prisma.XOR<Prisma.StyleCreateWithoutArtistsInput, Prisma.StyleUncheckedCreateWithoutArtistsInput>
}

export type StyleUpdateWithWhereUniqueWithoutArtistsInput = {
  where: Prisma.StyleWhereUniqueInput
  data: Prisma.XOR<Prisma.StyleUpdateWithoutArtistsInput, Prisma.StyleUncheckedUpdateWithoutArtistsInput>
}

export type StyleUpdateManyWithWhereWithoutArtistsInput = {
  where: Prisma.StyleScalarWhereInput
  data: Prisma.XOR<Prisma.StyleUpdateManyMutationInput, Prisma.StyleUncheckedUpdateManyWithoutArtistsInput>
}

export type StyleScalarWhereInput = {
  AND?: Prisma.StyleScalarWhereInput | Prisma.StyleScalarWhereInput[]
  OR?: Prisma.StyleScalarWhereInput[]
  NOT?: Prisma.StyleScalarWhereInput | Prisma.StyleScalarWhereInput[]
  id?: Prisma.IntFilter<"Style"> | number
  name?: Prisma.StringFilter<"Style"> | string
}

export type StyleUpdateWithoutArtistsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StyleUncheckedUpdateWithoutArtistsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StyleUncheckedUpdateManyWithoutArtistsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type StyleCountOutputType
 */

export type StyleCountOutputType = {
  artists: number
}

export type StyleCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  artists?: boolean | StyleCountOutputTypeCountArtistsArgs
}

/**
 * StyleCountOutputType without action
 */
export type StyleCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StyleCountOutputType
   */
  select?: Prisma.StyleCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StyleCountOutputType without action
 */
export type StyleCountOutputTypeCountArtistsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArtistWhereInput
}


export type StyleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  artists?: boolean | Prisma.Style$artistsArgs<ExtArgs>
  _count?: boolean | Prisma.StyleCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["style"]>

export type StyleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["style"]>

export type StyleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["style"]>

export type StyleSelectScalar = {
  id?: boolean
  name?: boolean
}

export type StyleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["style"]>
export type StyleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  artists?: boolean | Prisma.Style$artistsArgs<ExtArgs>
  _count?: boolean | Prisma.StyleCountOutputTypeDefaultArgs<ExtArgs>
}
export type StyleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type StyleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $StylePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Style"
  objects: {
    artists: Prisma.$ArtistPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["style"]>
  composites: {}
}

export type StyleGetPayload<S extends boolean | null | undefined | StyleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StylePayload, S>

export type StyleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StyleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StyleCountAggregateInputType | true
  }

export interface StyleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Style'], meta: { name: 'Style' } }
  /**
   * Find zero or one Style that matches the filter.
   * @param {StyleFindUniqueArgs} args - Arguments to find a Style
   * @example
   * // Get one Style
   * const style = await prisma.style.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StyleFindUniqueArgs>(args: Prisma.SelectSubset<T, StyleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StyleClient<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Style that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StyleFindUniqueOrThrowArgs} args - Arguments to find a Style
   * @example
   * // Get one Style
   * const style = await prisma.style.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StyleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StyleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StyleClient<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Style that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StyleFindFirstArgs} args - Arguments to find a Style
   * @example
   * // Get one Style
   * const style = await prisma.style.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StyleFindFirstArgs>(args?: Prisma.SelectSubset<T, StyleFindFirstArgs<ExtArgs>>): Prisma.Prisma__StyleClient<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Style that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StyleFindFirstOrThrowArgs} args - Arguments to find a Style
   * @example
   * // Get one Style
   * const style = await prisma.style.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StyleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StyleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StyleClient<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Styles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StyleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Styles
   * const styles = await prisma.style.findMany()
   * 
   * // Get first 10 Styles
   * const styles = await prisma.style.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const styleWithIdOnly = await prisma.style.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StyleFindManyArgs>(args?: Prisma.SelectSubset<T, StyleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Style.
   * @param {StyleCreateArgs} args - Arguments to create a Style.
   * @example
   * // Create one Style
   * const Style = await prisma.style.create({
   *   data: {
   *     // ... data to create a Style
   *   }
   * })
   * 
   */
  create<T extends StyleCreateArgs>(args: Prisma.SelectSubset<T, StyleCreateArgs<ExtArgs>>): Prisma.Prisma__StyleClient<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Styles.
   * @param {StyleCreateManyArgs} args - Arguments to create many Styles.
   * @example
   * // Create many Styles
   * const style = await prisma.style.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StyleCreateManyArgs>(args?: Prisma.SelectSubset<T, StyleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Styles and returns the data saved in the database.
   * @param {StyleCreateManyAndReturnArgs} args - Arguments to create many Styles.
   * @example
   * // Create many Styles
   * const style = await prisma.style.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Styles and only return the `id`
   * const styleWithIdOnly = await prisma.style.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StyleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StyleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Style.
   * @param {StyleDeleteArgs} args - Arguments to delete one Style.
   * @example
   * // Delete one Style
   * const Style = await prisma.style.delete({
   *   where: {
   *     // ... filter to delete one Style
   *   }
   * })
   * 
   */
  delete<T extends StyleDeleteArgs>(args: Prisma.SelectSubset<T, StyleDeleteArgs<ExtArgs>>): Prisma.Prisma__StyleClient<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Style.
   * @param {StyleUpdateArgs} args - Arguments to update one Style.
   * @example
   * // Update one Style
   * const style = await prisma.style.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StyleUpdateArgs>(args: Prisma.SelectSubset<T, StyleUpdateArgs<ExtArgs>>): Prisma.Prisma__StyleClient<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Styles.
   * @param {StyleDeleteManyArgs} args - Arguments to filter Styles to delete.
   * @example
   * // Delete a few Styles
   * const { count } = await prisma.style.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StyleDeleteManyArgs>(args?: Prisma.SelectSubset<T, StyleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Styles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StyleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Styles
   * const style = await prisma.style.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StyleUpdateManyArgs>(args: Prisma.SelectSubset<T, StyleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Styles and returns the data updated in the database.
   * @param {StyleUpdateManyAndReturnArgs} args - Arguments to update many Styles.
   * @example
   * // Update many Styles
   * const style = await prisma.style.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Styles and only return the `id`
   * const styleWithIdOnly = await prisma.style.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StyleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StyleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Style.
   * @param {StyleUpsertArgs} args - Arguments to update or create a Style.
   * @example
   * // Update or create a Style
   * const style = await prisma.style.upsert({
   *   create: {
   *     // ... data to create a Style
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Style we want to update
   *   }
   * })
   */
  upsert<T extends StyleUpsertArgs>(args: Prisma.SelectSubset<T, StyleUpsertArgs<ExtArgs>>): Prisma.Prisma__StyleClient<runtime.Types.Result.GetResult<Prisma.$StylePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Styles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StyleCountArgs} args - Arguments to filter Styles to count.
   * @example
   * // Count the number of Styles
   * const count = await prisma.style.count({
   *   where: {
   *     // ... the filter for the Styles we want to count
   *   }
   * })
  **/
  count<T extends StyleCountArgs>(
    args?: Prisma.Subset<T, StyleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StyleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Style.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StyleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StyleAggregateArgs>(args: Prisma.Subset<T, StyleAggregateArgs>): Prisma.PrismaPromise<GetStyleAggregateType<T>>

  /**
   * Group by Style.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StyleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StyleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StyleGroupByArgs['orderBy'] }
      : { orderBy?: StyleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StyleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStyleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Style model
 */
readonly fields: StyleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Style.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StyleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  artists<T extends Prisma.Style$artistsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Style$artistsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArtistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Style model
 */
export interface StyleFieldRefs {
  readonly id: Prisma.FieldRef<"Style", 'Int'>
  readonly name: Prisma.FieldRef<"Style", 'String'>
}
    

// Custom InputTypes
/**
 * Style findUnique
 */
export type StyleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * Filter, which Style to fetch.
   */
  where: Prisma.StyleWhereUniqueInput
}

/**
 * Style findUniqueOrThrow
 */
export type StyleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * Filter, which Style to fetch.
   */
  where: Prisma.StyleWhereUniqueInput
}

/**
 * Style findFirst
 */
export type StyleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * Filter, which Style to fetch.
   */
  where?: Prisma.StyleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Styles to fetch.
   */
  orderBy?: Prisma.StyleOrderByWithRelationInput | Prisma.StyleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Styles.
   */
  cursor?: Prisma.StyleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Styles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Styles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Styles.
   */
  distinct?: Prisma.StyleScalarFieldEnum | Prisma.StyleScalarFieldEnum[]
}

/**
 * Style findFirstOrThrow
 */
export type StyleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * Filter, which Style to fetch.
   */
  where?: Prisma.StyleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Styles to fetch.
   */
  orderBy?: Prisma.StyleOrderByWithRelationInput | Prisma.StyleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Styles.
   */
  cursor?: Prisma.StyleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Styles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Styles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Styles.
   */
  distinct?: Prisma.StyleScalarFieldEnum | Prisma.StyleScalarFieldEnum[]
}

/**
 * Style findMany
 */
export type StyleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * Filter, which Styles to fetch.
   */
  where?: Prisma.StyleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Styles to fetch.
   */
  orderBy?: Prisma.StyleOrderByWithRelationInput | Prisma.StyleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Styles.
   */
  cursor?: Prisma.StyleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Styles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Styles.
   */
  skip?: number
  distinct?: Prisma.StyleScalarFieldEnum | Prisma.StyleScalarFieldEnum[]
}

/**
 * Style create
 */
export type StyleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * The data needed to create a Style.
   */
  data: Prisma.XOR<Prisma.StyleCreateInput, Prisma.StyleUncheckedCreateInput>
}

/**
 * Style createMany
 */
export type StyleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Styles.
   */
  data: Prisma.StyleCreateManyInput | Prisma.StyleCreateManyInput[]
}

/**
 * Style createManyAndReturn
 */
export type StyleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * The data used to create many Styles.
   */
  data: Prisma.StyleCreateManyInput | Prisma.StyleCreateManyInput[]
}

/**
 * Style update
 */
export type StyleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * The data needed to update a Style.
   */
  data: Prisma.XOR<Prisma.StyleUpdateInput, Prisma.StyleUncheckedUpdateInput>
  /**
   * Choose, which Style to update.
   */
  where: Prisma.StyleWhereUniqueInput
}

/**
 * Style updateMany
 */
export type StyleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Styles.
   */
  data: Prisma.XOR<Prisma.StyleUpdateManyMutationInput, Prisma.StyleUncheckedUpdateManyInput>
  /**
   * Filter which Styles to update
   */
  where?: Prisma.StyleWhereInput
  /**
   * Limit how many Styles to update.
   */
  limit?: number
}

/**
 * Style updateManyAndReturn
 */
export type StyleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * The data used to update Styles.
   */
  data: Prisma.XOR<Prisma.StyleUpdateManyMutationInput, Prisma.StyleUncheckedUpdateManyInput>
  /**
   * Filter which Styles to update
   */
  where?: Prisma.StyleWhereInput
  /**
   * Limit how many Styles to update.
   */
  limit?: number
}

/**
 * Style upsert
 */
export type StyleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * The filter to search for the Style to update in case it exists.
   */
  where: Prisma.StyleWhereUniqueInput
  /**
   * In case the Style found by the `where` argument doesn't exist, create a new Style with this data.
   */
  create: Prisma.XOR<Prisma.StyleCreateInput, Prisma.StyleUncheckedCreateInput>
  /**
   * In case the Style was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StyleUpdateInput, Prisma.StyleUncheckedUpdateInput>
}

/**
 * Style delete
 */
export type StyleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
  /**
   * Filter which Style to delete.
   */
  where: Prisma.StyleWhereUniqueInput
}

/**
 * Style deleteMany
 */
export type StyleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Styles to delete
   */
  where?: Prisma.StyleWhereInput
  /**
   * Limit how many Styles to delete.
   */
  limit?: number
}

/**
 * Style.artists
 */
export type Style$artistsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Artist
   */
  select?: Prisma.ArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Artist
   */
  omit?: Prisma.ArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArtistInclude<ExtArgs> | null
  where?: Prisma.ArtistWhereInput
  orderBy?: Prisma.ArtistOrderByWithRelationInput | Prisma.ArtistOrderByWithRelationInput[]
  cursor?: Prisma.ArtistWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ArtistScalarFieldEnum | Prisma.ArtistScalarFieldEnum[]
}

/**
 * Style without action
 */
export type StyleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Style
   */
  select?: Prisma.StyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Style
   */
  omit?: Prisma.StyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StyleInclude<ExtArgs> | null
}
